faf-client:
  server:
    host: localhost

  irc:
    host: localhost

  ice:
    turn:
      host: localhost
    stun:
      host: localhost

  vault:
    base-url: http://content.faforever.com

  news:
    feed-url: http://direct.faforever.com/news/feed

  replay:
    remote-host: localhost

  api:
    base-url: http://localhost:8010
    access-token-uri: ${faf-client.api.base-url}/oauth/token
    client-id: 3bc8282c-7730-11e5-8bcf-feff819cdc9f
    client-secret: 6035bd78-7730-11e5-8bcf-feff819cdc9f

  forged-alliance:
    exe-url: http://content.faforever.com/faf/updaterNew/updates_faf_files/ForgedAlliance.exe
